name: Docker

on:
  workflow_call:
  

jobs:

  dokcer:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.12.0
      
    - name: Docker Login
      uses: docker/login-action@v3.6.0
      with:
        username: nikolassantos
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      uses: docker/build-push-action@v6.18.0
      with:
    # Build's context is the set of files located in the specified PATH or URL
        context: .
    # Path to the Dockerfile
        file: ./Dockerfile
    # Push is a shorthand for --output=type=registry
        push: true
    # List of tags
        tags: nikolassantos/go_ci:${{github.ref_name}}

          
